### ISSUE TITLE
Cloning luapower-repos gives ERROR: Invalid name

### ISSUE THREAD

**Issue by sumzary** [capr/multigit#12]
On my Ubuntu 16.04 machine I get `ERROR: Invalid name: 'luapower-repos'.`
Adding a backward dash before the '-' on this line fixes it.
`name="${name//[^.-_0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ]/}"` -->
`name="${name//[^.\-_0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ]/}"`

**Comment by capr** [comment]
thanks! fixed in git.
