### ISSUE TITLE
Is there a way to add support for topic branches, repos with multiple packages?

### ISSUE THREAD

**Issue by epcim** [capr/multigit#13]
Hi, I would like to use this tool to manage habitat.sh plans (https://github.com/epcim/habitat-plans).

I actually got exactly the same idea with worktree as you. But its bit more complex. With "topic branch" in title I mean be able to "use" individual plans (directories) from shared source (https://github.com/habitat-sh/core-plans) and keep an option to provide back the PR with changes I made.

What would be a way to add support for the following use-case?
(understand: habitat-plan repositories are usually not per "plan" but a repo of multiple plans together.)
I have to fork/fetch the upstream, create a branch like (core_<topic>, in example: core_etcd) and then finally use mgit to clone it, but at best link just one directory).

Actually, to make things more simple, I don't have to fork upstream (on GH for example), I may just "create new remote" and use `git fetch --all` then.

Finally, to `pick` just one directory (for example just etcd) from https://github.com/habitat-sh/core-plans I may use just a symlink to a given $worktree/core/etcd.

Any ideas? Too insane? Feedback welcome.

**Comment by capr** [comment]
So you basically want to check out only a subdirectory of a repo into the worktree?

**Comment by epcim** [comment]
Yes
And at best, have for this directory worktree branch. It can be done like ‘git worktree add -b core/etcd —track core/master worktree/path/tofetchtoe’ assuming assuming from last I will only add that ne directory (or link it)

**Comment by capr** [comment]
Why don't you split the repo into multiple repos then? I think I'm missing something here...

**Comment by epcim** [comment]
As I dont own the remote repo. I count to do that with mine. But unless its recognized best practice there will be mixed variants. I am testing my own script now. I was basically interested whether mgit could support such case. On 11 Jun 2018 23:28, Cosmin Apreutesei <notifications@github.com> wrote:Why don't you split the repo into multiple repos then? I think I'm missing something here...

**Comment by capr** [comment]
Looks like they added this last year https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository/52269934#52269934

closing this...
