### ISSUE TITLE
Unclear how to push into one git repo

### ISSUE THREAD

**Issue by deminngi** [capr/multigit#15]
@capr Can you explain a little bit more deeply 
- how can I pull/push to git if I have multiple layered projects using branches using one git repo
- how to merge/manage all subprojects into one git repo
- how to use make-sym-/hardlinks

project (main-git-repo)
I---+ some files
I-----subdir (e.g. subproject directory)
I--------I-----+ sub-repo  (specific subproject repo)
I--------------------I-----+ some files (specific subproject files)
I--------I-----+ sub-repo  (specific subproject repo)
I--------------------I-----+ some files (specific subproject files)

thx.

**Comment by chminngi** [comment]
Found the answer by myself.
