### ISSUE TITLE
Can I mgit clone with --depth 1 option?

### ISSUE THREAD

**Issue by petr-fischer** [capr/multigit#16]
How to use "--depth 1" option when cloning mgit repo? Is it possible?

**Comment by capr** [comment]
This is the code that does cloning:

	# finally, clone the repo
	no_exclude_file=1 init "$name" || return
	git remote add origin "$url"
	git fetch $MULTIGIT_FETCH_OPTS || {
		rm -rf ".mgit/$name/"
		rm ".mgit/$name.exclude"
		echo "ERROR: Fetch failed. Repo removed."
		return
	}
	git branch --track master origin/master
	git checkout $ver

If --depth is an option on any of these commands then you could modify the script to accept that.

**Comment by capr** [comment]
Looks like fetch allows `--depth`, so you could do something like :

`MULTIGIT_FETCH_OPTS=--depth=1 mgit clone foo`
