### ISSUE TITLE
Using submodules in multiple repos

### ISSUE THREAD

**Issue by infokiller** [capr/multigit#17]
Is there any way to use submodules in multiple repos, similar to the gitignore trick?

Thanks!

**Comment by capr** [comment]
Hmm, dunno, I never used them. To me overlaid repos are strictly more powerful than submodules and without having to learn new git syntax or semantics.

**Comment by infokiller** [comment]
Overlaid repos are indeed useful (I use them myself to separate my dotfiles into public and private repos, though without multigit). However, I disagree that they are strictly better than submodules. Here are some of the things that make me prefer submodules in some situations:

- They are built into git, so you can use them without any utility scripts.
- Their syntax/semantics are very minimal, there's almost nothing to learn. I would argue that multiple repos managed with `GIT_DIR` are actually more complex for a user.
- No need for hacks to use separate gitignore file, which means that the gitignore is properly checked in to the repo and works automatically after cloning, and you don't need to set the local git config.
- You use plain unambiguous git commands without the need to set `--git-dir`/`GIT_DIR`, which also means you don't to deal with issues such as files being added to multiple repos (or added to the wrong repo, or deleted from multiple repos, or...)
- You can manage all your dependencies atomically. You have a single commit (of the superproject) that defines the exact project state (that is, all the files in both the project and its submodules). So people can just do `git clone --recursive` and they end up with the exact state the project author intended, no additional tooling needed.

**Comment by capr** [comment]
I didn't say they are better, I said that _to me_ they are more _powerful_ meaning you can do things with overlaid repos that you cannot do with submodules (otherwise there would be no point for this project).

**Comment by infokiller** [comment]
I know you didn't say that, but I felt this was implied. Anyway, I wasn't trying to convince you to use submodules (you whatever works for you of course), I was just trying to provide a different perspective on where submodules can be better.
