### ISSUE TITLE
How to find out which repository owns a modified files?

### ISSUE THREAD

**Issue by wdicarlo** [capr/multigit#5]
I have modifed a file but it seems it is not possible to find how which repository own it. Am I missing something or it is needed a command to list the repository owning a file/files?

**Comment by capr** [comment]
I added ls-tracked option, see: 24c7f84f063f3d383c2905567c55525cd3056d51

So now you can say `mgit ls-tracked | grep <file>` (note: it's slow if you have hundreds of repos because it has to `git ls-files` them all)

thanks for the idea btw!

**Comment by wdicarlo** [comment]
I see, good job. The only thing I would add is a way to easily identify the names of the repositories like `@reponame:`. For example with the command `mgit --all status` you could get something like the following

> @socket:
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> nothing to commit, working directory clean
> @lpeg:
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> Changes not staged for commit:
>  (use "git add <file>..." to update what will be committed)
>  (use "git checkout -- <file>..." to discard changes in working directory)
> 
>   modified:   re.lua
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> @lua-headers:
> On branch master
> Your branch is up-to-date with 'origin/master'.
> 
> nothing to commit, working directory clean

Then one could find the modified file with `mgit --all status | grep "^@.*:\|modified"`

> @lfs:
> @lpeg:
>   modified:   re.lua
> @lua-headers:
> @luajit:
> @socket:

Regards

**Comment by capr** [comment]
I just added `--all -v` option for that. I tried to make the `@repo:` line print only if the command had any output but I couldn't figure it out how to do it without losing colors, so I removed that bit.
