### ISSUE TITLE
Only lowercase letters for repo name?

### ISSUE THREAD

**Issue by petr-fischer** [capr/multigit#9]
Hello, why only lowercase letters for repo name?

In init, there is 
```
name="${name//[^-_0123456789abcdefghijklmnopqrstuvwxyz]/}"
```
Is possible to extend this with uppercase letters? What about camelCase repo names? :) Any issues with this?

**Comment by petr-fischer** [comment]
Added pull request #10

**Comment by capr** [comment]
Thanks for the fix.
